CKPTS_FOLDER = 'ckpts'
TMP_FOLDER = 'tmp'
TEST_FILE = f'{TMP_FOLDER}/test.csv'
DEV_FILE = f'{TMP_FOLDER}/dev.csv'
IDX2LABELS_FILE = f'{TMP_FOLDER}/idx2labels4.txt'
RAW_INTERNAL_FILE = f'{TMP_FOLDER}/raw.csv'
CHECKPOINT_FILE = f"{CKPTS_FOLDER}/fre-BERTBiLSTMAttnCRF-dev.cpt"
NUM_EPOCHS = 100